# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxbot
  labels:
    app.kubernetes.io/part-of: linuxbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linuxbot-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linuxbot-app
        app.kubernetes.io/part-of: linuxbot
    spec:
      containers:
      - args:
        - streamlit run app.py --server.port 8080
        env:
        - name: OLLAMA_HOST
          value: ollama
        image: quay.io/sroecker/linuxbot-app:latest
        imagePullPolicy: Always
        name: linuxbot
        ports:
        - containerPort: 8080
          name: frontend
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/shm
          name: shm
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
---
# Service linuxbot-app
apiVersion: v1
kind: Service
metadata:
  name: linuxbot
  labels:
    app.kubernetes.io/part-of: linuxbot
spec:
  selector:
    app: linuxbot-app
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: frontend
---
# Route 
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: linuxbot-app
  labels:
    app: linuxbot-app
    app.kubernetes.io/part-of: linuxbot
spec:
  host: linuxbot.apps.cluster-xv6h4.xv6h4.sandbox255.opentlc.com
  to:
    kind: Service
    name: linuxbot
    weight: 100
  port:
    targetPort: '8080'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
